version: '3'

services:
  postgres-compose:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15432:5432"
    volumes:
      - /home/docker/postgresql-data:/var/lib/postgresql/data 
    networks:
      - postgres-network
      
  pgadmin-compose:
    image: dpage/pgadmin4:4.15
    environment:
      PGADMIN_DEFAULT_EMAIL: "pauluscave@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    volumes:
      - /home/docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres-compose
    networks:
      - postgres-network

networks: 
    postgres-network:
